/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello.world

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val x = 3
    val y = 5

    if ( x > y ) {
        println("x greater than y")
    }
    else if ( x < y) {
        println("x less than y")
    }
    else
        println("x equals y")

    println("----------------")
    var index = 0
    while ( index < 5 ) {
        println(index)
        index++
    }


    println("----------------")
    val ia: IntArray = intArrayOf(3, 5, 7)
    var total: Int = 0
    for ( n in ia ) {
        total += n
    }
    println("Total: $total")

    println("----------------")
    val ib: IntArray = intArrayOf(120, 30, 15, 27, 66)
    ib.filter { it > 50 }
        .sortedBy { it }
        .map { it / 10 }
        .forEach { print("$it-")}
}
