/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello.world

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val x = 3
    val y = 5
    val z = 7

    var s = "X: $x, Y: $y, Z: $z"
    println(s)
    println("summary: $x + y + z")
    println("summary: ${x + y +z}")
}
